config/routes.rb
NinetyNineCats::Application.routes.draw do
  resources :cats
  resources :users, only: [:new, :create]
  resources :cat_rental_requests do
    member do
      put 'approve'
      put 'deny'
    end
  end
  
  resource :session
end

app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = %w[red orange yellow green blue black]
  
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id
  validates :age, :birth_date, :color, :name, :sex, :user_id, presence: true
  validates :age, :user_id, numericality: true
  validates :color, inclusion: { in: COLORS }
  validates :sex, inclusion: { in: %w[M F] }
  
  has_many(
  :rental_requests,
  :class_name => "CatRentalRequest",
  :foreign_key => :cat_id,
  :primary_key => :id,
  :order => "start_date ASC",
  :dependent => :destroy
  )
  
  belongs_to(
  :owner,
  :class_name => "User",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  def has_pending_requests?
    self.rental_requests.any? { |request| request.status == "PENDING" }
  end
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :status, :start_date, :end_date
  validates :cat_id, :status, :start_date, :end_date, presence: true
  validates :status, inclusion: { in: %w[PENDING APPROVED DENIED] }
  before_validation(on: :create) do
    self.status ||= "PENDING"
  end
  
  belongs_to(
  :cat,
  :class_name => "Cat",
  :foreign_key => :cat_id,
  :primary_key => :id
  )


  def overlapping_requests
    CatRentalRequest.find_by_sql([<<-SQL, self.cat_id, self.id, self.start_date, self.end_date, self.start_date, self.end_date, self.start_date, self.end_date])
    SELECT
    *
    FROM
    cat_rental_requests
    WHERE
    cat_id = ? AND
    id <> ? AND 
    ((start_date between ? AND ?) OR (end_date between ? AND ?) OR (start_date < ? AND end_date > ?))
    SQL
  end
  
  def overlapping_approved_requests
    overlapping_requests.select { |request| request.status == "APPROVED" }
  end
  
  def overlapping_pending_requests
    overlapping_requests.select { |request| request.status == "PENDING" }
  end
  
  def approve!
    transaction do
      self.status = "APPROVED"
      self.save!
    
      self.overlapping_pending_requests.each do |request|
        request.deny!
      end
    end
  end
  
  def deny!
    self.status = "DENIED"
    self.save!
  end
  
  def pending?
    self.status == "PENDING"
  end
  
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  attr_accessible :user_name, :password_digest, :password
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, :session_token, uniqueness: true
  before_validation(on: :create) do
    self.reset_session_token! if !self.session_token
  end
  
  has_many(
  :cats,
  :class_name => "Cat",
  :foreign_key => :user_id,
  :primary_key => :id
  )
  
  def reset_session_token!
    self.session_token = SecureRandom::urlsafe_base64(16)
    self.save!
  end
  
  def password=(password)
    self.password_digest = BCrypt::Password.create(password)
  end
  
  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end
  
  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)
    if user
      user.is_password?(password) ? user : nil
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :require_owner_for_approval!, only: [:approve, :deny]
  
  def new
    @cats = Cat.all
    
    render :new
  end
  
  def create
    @request = CatRentalRequest.new(params["cat_rental_request"])
    @request.save!
    cat = @request.cat
    
    redirect_to cat_url(cat)
  end
  
  def approve
    @request = CatRentalRequest.find(params[:id])
    @request.approve!
    cat = @request.cat
    
    redirect_to cat_url(cat)
  end
  
  def deny
    @request = CatRentalRequest.find(params[:id])
    @request.deny!
    cat = @request.cat
    
    redirect_to cat_url(cat)
  end
  
  private
  
  def current_request
    @current_request ||= CatRentalRequest.find(params[:id])
  end
  
  def cat_requested
    Cat.find(current_request.cat_id)
  end
  
  def require_owner_for_approval!
    #flash error
    redirect_to cat_url(cat_requested) unless cat_requested.owner == current_user
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :require_proper_owner!, only: [:edit, :update]
  
  def index
    @cats = Cat.all
    
    render :index
  end
  
  def show
    @cat = Cat.find(params[:id])
    
    render :show
  end
  
  def new
    @cat = Cat.new
    @colors = Cat::COLORS
    
    render :new
  end
  
  def edit
    @cat = Cat.find(params[:id])
    @colors = Cat::COLORS
    
    render :edit
  end
  
  def update
    @cat = Cat.find(params[:id])
    @cat.update_attributes(params["cat"])
    
    redirect_to cat_url(@cat)
  end
  
  def create
    @cat = Cat.new(params["cat"])
    @cat.user_id = current_user.id
    @cat.save!
    
    redirect_to cat_url(@cat)
  end
  
  private
  
  def current_cat
    @current_cat ||= Cat.find(params[:id])
  end
  
  def require_proper_owner!
    redirect_to cat_url(current_cat) unless current_cat.owner == current_user
  end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(params["user"]["user_name"], params["user"]["password"])
    if user
      login_user!(user)
      redirect_to cats_url
    else
      redirect_to new_session_url
    end
  end
  
  def new
    # @user = User.new
    
    render :new
  end
  
  def destroy
    current_user.reset_session_token!
    session[:session_token] = nil
    
    redirect_to cats_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    render :new
  end
  
  def create
    @user = User.new(params["user"])
    if @user.save
      login_user!(@user)
      redirect_to cats_url
    else
      redirect_to new_user_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end
  
  def login_user!(user)
    user.reset_session_token!
    session[:session_token] = user.session_token
  end
end

app/views/cat_rental_requests/new.html.erb
<h2>Create Cat Rental Request Form</h2>

<form action="<%= cat_rental_requests_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
         
  <label for="cat_rental_request_cat_id">Desired cat</label>
  <select name="cat_rental_request[cat_id]" id="cat_rental_request_cat_id">
    <option></option>
    <% @cats.each do |cat| %>
    <option value=<%= cat.id %>><%= cat.name %></option>
    <% end %>
  </select>
  <br>
  <br>
  
  <label for="cat_rental_request_start_date">Start date</label>
  <input name="cat_rental_request[start_date]" id="cat_rental_request_start_date" type="date">
  <br>
  <br>
  
  <label for="cat_rental_request_end_date">End date</label>
  <input name="cat_rental_request[end_date]" id="cat_rental_request_end_date" type="date">
  <br>
  <br>
  
  <input type="submit" value="Submit">
</form>

app/views/cats/_form.html.erb
<% action = cat.persisted? ? cat_url(cat) : cats_url %>
<% submit_value = cat.persisted? ? "Edit my cat!" : "Create my cat!"%>

<% if cat.persisted? %>
<h2>Edit <%= cat.name.capitalize + "'s Info" %></h2>
<% else %>
<h2>Create new cat</h2>
<% end %>
<form action="<%= action %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
         
  <% if cat.persisted? %>
  <input type="hidden" name="_method" value="put">
  <% end %>
  
  <label for="cat_name">Name</label>
  <input name="cat[name]" id="cat_name" type="text" value="<%= cat.name %>">
  <br>
  
  <label for="cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="number" value="<%= cat.age %>">
  <br>
  
  <label for="cat_birth_date">Birthdate</label>
  <input name="cat[birth_date]" id="cat_birth_date" type="date" value="<%= cat.birth_date %>">
  <br>
  <br>
  
  <label>Sex</label>
  <div>
    <label for="cat_sex_m">Male</label>
    <input name="cat[sex]" id="cat_sex_m" type="radio" value="M" <%= "checked" if cat.sex == "M" %>> 
    <label for="cat_sex_f">Female</label>
    <input name="cat[sex]" id="cat_sex_f" type="radio" value="F" <%= "checked" if cat.sex == "F" %>>  
  </div>
  <br> 
  
  
  <label for="cat_color">Color</label>
  <select name="cat[color]">
    <option></option>
    <% @colors.each do |color| %>
    <option value="<%= color %>" <%= "selected" if cat.color == color %>><%= color.capitalize %></option>
    <% end %>
  </select>
  <br>
  <br>
  
  <input type="submit" value="<%= submit_value %>">
</form>
  
  
  
  

app/views/cats/edit.html.erb
<%= render "form", :cat => @cat %>

app/views/cats/index.html.erb
<h2>Cats</h2>

<ul>  
  <% @cats.each do |cat |%>
    <li><%= link_to "#{cat.name}", cat_url(cat) %></li>
  <% end %>
</ul>

<%= button_to("Create rental request", new_cat_rental_request_url, method: :get) %>

app/views/cats/new.html.erb
<%= render "form", :cat => @cat %>

app/views/cats/show.html.erb
<%= link_to("Return to cat index", cats_url, method: :get) %>

<h2><%= @cat.name + "'s Vital Info" %></h2>
<table border="2">
  <tr>
    <td>Name</td>
    <td><%= @cat.name %></td>
  </tr>
  <tr>
    <td>Age</td>
    <td><%= @cat.age %></td>
  </tr>
  <tr>
    <td>Birthdate</td>
    <td><%= @cat.birth_date %></td>
  </tr>
  <tr>
    <td>Color</td>
    <td><%= @cat.color %></td>
  </tr>
  <tr>
    <td>Sex</td>
    <td><%= @cat.sex %></td>
  </tr>
</table>
<br>

<h3>Rental Requests</h3>
<table border="2">
  <tr>
    <td>Start date</td>
    <td>End date</td>
    <td>Status</td>
    <% if @cat.has_pending_requests? && @cat.owner == current_user %>
    <td>Approve?</td>
    <td>Deny?</td>
    <% end %>
  </tr>
  <% @cat.rental_requests.each do |request| %>
  <tr>
    <td>&nbsp;&nbsp;<%= request.start_date %>&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;<%= request.end_date %>&nbsp;&nbsp;</td>
    <td>&nbsp;&nbsp;<%= request.status %>&nbsp;&nbsp;</td>
    <% if request.pending? && @cat.owner == current_user && @cat.has_pending_requests? %>
    <td>
      <%= button_to "Approve", "/cat_rental_requests/#{request.id}/approve", :method => :put %>
    </td>
    <td>
      <%= button_to "Deny", "/cat_rental_requests/#{request.id}/deny", :method => :put %>
    </td>
    <% end %>
  </tr>
  <% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if !current_user %>
  <%= button_to("Sign in", new_session_url, :method => :get) %>
  <%= button_to("Register", new_user_url, :method => :get) %>
  <% else %>
  <%= "Welcome back #{current_user.user_name}!" %>
  <%= button_to("Sign out", session_url, :method => :delete) %>
  <% end %>

<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h2>Create new user</h2>

<form action="<%= users_url %>" method="post">
  <input type="hidden"
         name="authenticity_token"
         value="<%= form_authenticity_token %>">
         
  <label for="user_user_name">Username</label>
  <input name="user[user_name]" type="text" id="user_user_name">
  <br>
  
  <label for="user_password">Password</label>
  <input name="user[password]" type="text" id="user_password">
  <br>
  <input type="submit" value="Submit">
</form>